#!/usr/bin/env bash
# gen-projects-registry: emit ~/.claude/PROJECTS.md — a cross-project map
# (name · path · one-liner) so every Claude session knows sibling projects and
# where their folders live. Project root is read from the transcript `cwd`
# field (deterministic); decoding the project-dir slug is lossy (dashes are
# ambiguous and worktree sessions point elsewhere), so cwd is authoritative.
# Called by graphify-sync.sh; safe to run standalone.
set -uo pipefail

PROJECTS_DIR="$HOME/.claude/projects"
OUT="$HOME/.claude/PROJECTS.md"

python3 - "$PROJECTS_DIR" "$OUT" <<'PY'
import json, sys
from pathlib import Path

projects_dir = Path(sys.argv[1])
out = Path(sys.argv[2])

def first_cwd(jsonl):
    try:
        with open(jsonl) as fh:
            for line in fh:
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                if d.get("cwd"):
                    return d["cwd"]
    except OSError:
        return None
    return None

GENERIC = {"memory index", "memory", "auto memory"}

def first_desc(memdir):
    # First markdown H1 only; skip generic index titles.
    f = memdir / "MEMORY.md"
    if not f.is_file():
        return None
    try:
        for line in f.read_text(errors="ignore").splitlines():
            if line.startswith("# "):
                s = line.lstrip("#").strip()
                if s and s.lower() not in GENERIC:
                    return s
                return None
    except OSError:
        return None
    return None

entries = {}  # resolved path -> (name, desc, mtime)
skipped = []  # (name, path) whose folder no longer exists
for d in sorted(projects_dir.iterdir()):
    if not d.is_dir():
        continue
    memdir = d / "memory"
    if not (memdir / "MEMORY.md").is_file():
        continue  # only projects with accumulated memory
    jsonls = sorted(d.glob("*.jsonl"), key=lambda p: p.stat().st_mtime, reverse=True)
    cwd = first_cwd(jsonls[0]) if jsonls else None
    if not cwd:
        cwd = "/" + d.name.lstrip("-").replace("-", "/")  # lossy fallback
    name = Path(cwd).name
    if not Path(cwd).is_dir():
        skipped.append((name, cwd))  # retired/moved project; memory lingers
        continue
    desc = first_desc(memdir) or ""
    mtime = jsonls[0].stat().st_mtime if jsonls else 0
    prev = entries.get(cwd)
    if prev is None or mtime > prev[2]:
        entries[cwd] = (name, desc, mtime)

lines = [
    "# Projects map",
    "",
    "Auto-generated by gen-projects-registry.sh (graphify-sync). Lists every",
    "project with accumulated memory: folder path + one-line summary. Use this to",
    "know a sibling project exists and where it lives; query the graphify-memory",
    "MCP for depth on any entry.",
    "",
]
for cwd in sorted(entries, key=lambda p: entries[p][0].lower()):
    name, desc, _ = entries[cwd]
    line = f"- **{name}** · `{cwd}`"
    if desc:
        line += f" — {desc}"
    lines.append(line)
lines.append("")
out.write_text("\n".join(lines))
msg = f"[gen-projects-registry] wrote {len(entries)} project(s) -> {out}"
if skipped:
    msg += f"; skipped {len(skipped)} with missing folder: " + ", ".join(n for n, _ in skipped)
print(msg)
PY
